### PR TITLE
Fix #190 #192

### LINKED ISSUE #190: Distinguish different types of blocks for indentation?
Currently we treat all blocks similarly. Particularly with `ess-offset-block` set to `(t)` we get:

```
r <- funcall(if (cond1)
    stuff1
else if (cond2)
    stuff2
else
    stuff3)
```

How big of a problem is this? Do we really need to differentiate different blocks? And if so, how?

### PR DESCRIPTION
**Pull request by lionel-**
Here are the updates for the last discussions including the one in #189.

About the overrides for blocks, I implemented it as a list because it was easy enough, and on second thought I think it can be useful. This way we allow both if-else blocks and function declaration blocks to be aligned vertically. It makes sense that some users may want indentation at prev-line of blocks in general (for the `test_that` DSL for example) but still want their lambda functions to be indented in a compact way. In particular, some users like to have code in function arguments (cf Martin's example with an if-else block as default function argument), and it looks better to have vertical alignment in this case.

But if you object I can change it to a boolean.

### CODE REVIEW

**Comment by vspinu** [comment]
Everything looks ok except my minor comments.

> This way we allow both if-else blocks and function declaration blocks to be aligned vertically. 

List is ok with me. Could you please give an example of `fun-decl` settings? I am not sure I understand what you mean.

**Comment by lionel-** [comment]
> Could you please give an example of fun-decl settings?

For example with `arg1` here:
```r
{
   fun <- function(arg1 = function() {
                             body
                          },
                   arg2 = if (cond) {
                              stuff1
                          } else {
                              stuff2
                          })
}
```

**Comment by vspinu** [comment]
So `fun-decl` refers to the function declaration inside a function declaration only?

How about:

```
fun <- fun_call(arg1 = function() {
    body
})
```
?

**Comment by vspinu** [comment]
More concretely, what is the relationship to `ess-indent-align-declaration-args`. Do we still need it if we have `fun-decl` option?

**Comment by lionel-** [comment]
> So fun-decl refers to the function declaration inside a function declaration only?

No, to any function call, so your example becomes

```r
fun <- fun_call(arg1 = function() {
                           body
                       })
```

**Comment by lionel-** [comment]
the `misc1.R` contains some examples of that

**Comment by vspinu** [comment]
Ok. I am clarified now. We basically converged on having `ess-indent-align-xxx` to fine tune other offsets in a specific vertical pattern.  That's not bad, I think.

**Comment by lionel-** [comment]
now that we have a bunch of `align-` setting, I wonder if we should rename them to `ess-align-` for the sake of shorter variable names?

**Comment by vspinu** [comment]
> now that we have a bunch of align- setting, I wonder if we should rename them to ess-align- for the sake of shorter variable names?

Yes. I don't mind. It's also better for the documentation We can document them inside a separate group in `ess-style-alist`.

**Comment by lionel-** [comment]
Here you go Vitalie

**Comment by vspinu** [comment]
Great! Thanks.

With this we are pretty much done, right? Or, is there any other urgent indentation issues that should be fixed by the next `15.09` release?

**Comment by lionel-** [comment]
we're good for now! :)

**Pull request merged**
