### PR TITLE
Remove inferior-*-start-file

### PR DESCRIPTION
**Pull request by jabranham**
I don't think it's respected anyway since the customize-alists override it with `nil` in almost all cases.

### CODE REVIEW

**Comment by jabranham** [comment]
> Not in case of STATA files.

Right, that's why I said "almost" :-)

> Why removing and not fixing?

Users can achieve the same thing by using `ess-load-file` and the various `-post-run-hook`s. I could add a comment about this to the manual, if needed?

**Comment by vspinu** [comment]
True, though it requires some, admittedly trivial, lisp. I am indifferent about this feature and would be ok with removing it if others don't mind.

**Comment by lionel-** [comment]
I think simplifying the internals and the interface of ESS and teaching users about ESS hooks and functions in the manual is a win-win.

**Comment by jabranham** [comment]
I've added some documentation to the manual about how to do that. I'll merge this soonish unless someone objects.

**Pull request merged**
