### PR TITLE
Make ess-r-versions a defcustom

### PR DESCRIPTION
**Pull request by jabranham**
This lets us use the :set keyword to monitor when it changes so that we can update the runners. See #857.

### CODE REVIEW

**Comment by jabranham** [comment]
Actually I don't think this will work as is. Will have to take a closer look later

**Comment by jabranham** [comment]
Alright, should be ready now I think.

**Comment by vspinu** [comment]
Shall we change the name on this occasion? I have no good ideas, but something more intuitive, like `executable-names` or `executable-prefixes` could be more appropriate.

**Comment by jabranham** [comment]
I don't have a great idea, but how about any of these?

- ess-r-executable-versions
- ess-r-program-versions
- ess-r-versions-regexp
- ess-r-command-regexps

Though TBH I'm not sure if any of those are better than ess-r-versions...

**Comment by lionel-** [comment]
I like `ess-r-program-versions`. Or perhaps `ess-r-runner-versions` to connect with `ess-r-runners`?

**Comment by mmaechler** [comment]
> I like `ess-r-program-versions`. Or perhaps `ess-r-runner-versions` to connect with `ess-r-runners`?

Good point to bring "runners" into play.  Note that we have `(defun ess-r-define-runners ....)` [which uses `(defun ess-define-runner ...)`  and its result stored/cached in variable  `ess-r-created-runners' .. so I'd came to
`ess-r-runner-prefixes` or  `ess-r-prefix-runners`  [the latter because all current `*runner*` names end in `runner` or `runners`.

Note that "program-versions" is misleading too. This is really the variable with the **prefixes** and defaults such as "R-2" "R-3" ..

**Comment by mmaechler** [comment]
what about `ess-r-runner-prefixes`  ?   A day later it seems the most  consistent and nice..

**Comment by jabranham** [comment]
Sounds good to me. I'll make that change and merge this later today unless
I hear otherwise from someone.

**Comment by vspinu** [comment]
Good idea. `ess-r-runners-prefixes` seems to nail it.

**Pull request merged**
