### PR TITLE
Add test for ess-smart-S-assign

### PR DESCRIPTION
**Pull request by jabranham**
I'm trying to be better about writing tests for things I change. Here's one for the recently-changed `ess-smart-S-assign`.

### CODE REVIEW

**Comment by jabranham** [comment]
The failing test seems to be a travis network error, just FYI. 

Is it not possible to make travis re-run tests?

**Comment by lionel-** [comment]
Thanks! You can amend and force-push to trigger a new build. Just restarted.

**Comment by jabranham** [comment]
Thanks, seems to be fixed now.

**Comment by vspinu** [comment]
Cool. Thanks!

**Comment by lionel-** [comment]
I hadn't look at the changes yet. I'm a bit concerned about the redundancy between this macro and the literate tests. I guess it's ok. But at least the point sentinel should be made consistent, the literate tests use `¶` rather than `<point>`.

**Pull request merged**
