### PR TITLE
Make 'ess-process-name-list' a list of strings

### PR DESCRIPTION
**Pull request by jabranham**
Also rename 'update-ess-process-name-list' to
'ess-update-process-name-list'.

Tagging @lionel- since you initially added the FIXME

### CODE REVIEW

**Comment by lionel-** [comment]
If we're changing the internals without thinking about backward compat, we should namespace these symbols in `ess--`. I'm sligthly worried that people might be using those for managing and querying inferiors, either in packages or in scripts. Perhaps we should also think about whether a list of inferior buffers might not be a more appropriate representation. In general it feels like such a refactoring should be part of a larger rethinking of inferior management, otherwise it's not necessarily worth it.

**Comment by jabranham** [comment]
I wonder if it makes sense to obsolete that variable and just dynamically generate that list as needed?

**Comment by vspinu** [comment]
I would say we either make it go away completely or don't touch it for now. That's a rudimentary process tracking which is done by sesman and will go away anyhow.

**Comment by jabranham** [comment]
OK, I will close this then.

**Pull request closed without merging**
