### PR TITLE
Add tests for runners

### PR DESCRIPTION
**Pull request by jabranham**
Please don't merge this yet. I'm not 100% happy with how we setup a fake R executable on travis. It would be nice to be able to run these tests locally somehow but I haven't gotten around to doing that yet. If you've got any ideas, let me know.

-----

Adding tests for runners as a part of #672

### CODE REVIEW

**Comment by jabranham** [comment]
In the spirit of "something is better than nothing," I'm going to go ahead and merge this.

**Comment by lionel-** [comment]
Vaguely related, but eventually it might make sense to install R-devel and rerun all our inferior-based tests on R-devel to catch regressions before they make their way into a release. I'm thinking about the dump-to-buffer regression for instance.

**Comment by jabranham** [comment]
I've looked into that a bit and the biggest hurdle is getting an R-devel
binary that's updated.

**Comment by lionel-** [comment]
We should probably use the same binary as r-travis uses.

**Comment by jabranham** [comment]
I looked into that a while ago but forgot why I didn't like it. :-/

**Comment by vspinu** [comment]
I am not sure if it's worth it. These ess-runners constitute a small piece of functionality and pulling R-devel on travis would increase test times considerably. 

Having said that, devtools has just changed user API in devel and we almost missed that for next release. So having some long term solution for R-side testing would be nice in principle. On the other hand, if a few of us sit on R-devel and devtools-devel then we should be fine as well.

**Pull request merged**
