### PR TITLE
Remove many unused files

### PR DESCRIPTION
**Pull request by jabranham**
I don't see any of these used anywhere. Is there a reason to keep some/all/none of them?

```
* .gitignore: Remove *NEWS

* doc/archive/OONEWS:
* doc/archive/rsn.txt: Rename from top-level

* fontlock-test/baseball.sas:
* fontlock-test/elem.sas:
* fontlock-test/runif.Rcxx:
* fontlock-test/testing.sas:
* install-sh:
* lisp/old/ess-debug.el:
* lisp/old/ess-install.el:
* lisp/old/ess-old-contrib.el:
* lisp/old/ess-old-s.el:
* lisp/old/ess-old-site.el:
* lisp/old/ess-send.el:
* lisp/old/ess-send2.el:
* lisp/tmp/ess-dump.el:
* lisp/tmp/ess-rlib.R:
* lisp/tmp/ess-rlib.el:
* mkinstalldirs: Remove
```

### CODE REVIEW

**Comment by jabranham** [comment]
@vspinu OK, I didn't know how aggressively we wanted to clean. I pushed a second commit that removes a lot more:

```
* doc/Makefile: Modify to account for dir.txt removal

* etc/pkg-Maintainers: 
* doc/ChangeLog: 
* doc/TODO: 
* doc/archive/ESS_intro.tex: 
* doc/archive/OONEWS: 
* doc/archive/README.Microsoft: 
* doc/archive/README.Microsoft.texi: 
* doc/archive/README.S: 
* doc/archive/README.SAS: 
* doc/archive/README.SPLUS4COMMAND: 
* doc/archive/README.SPLUS4WIN: 
* doc/archive/README.Windows: 
* doc/archive/README.XLispStat: 
* doc/archive/README.additions: 
* doc/archive/README.elsewhere: 
* doc/archive/README.noweb.ESS: 
* doc/archive/Why_R_mode_not_S_mode.txt: 
* doc/archive/Why_S-mode_Rocks.DMS: 
* doc/archive/ajr-talk.tex: 
* doc/archive/bugs-ms.texi: 
* doc/archive/ediff-sas.gif: 
* doc/archive/ediff-sas.pdf: 
* doc/archive/ess-demo.jpg: 
* doc/archive/ess-demo.pdf: 
* doc/archive/ess-intro-graphs.bib: 
* doc/archive/ess-intro-graphs.pdf: 
* doc/archive/ess-intro-graphs.tex: 
* doc/archive/ess-intro.pdf: 
* doc/archive/ess-intro.tex: 
* doc/archive/ess-manual.org: 
* doc/archive/font-cor-s.gif: 
* doc/archive/font-cor-s.jpg: 
* doc/archive/font-cor-s.pdf: 
* doc/archive/font-incor-s.gif: 
* doc/archive/font-incor-s.jpg: 
* doc/archive/font-incor-s.pdf: 
* doc/archive/hilock-sas.gif: 
* doc/archive/hilock-sas.pdf: 
* doc/archive/include-matrix.org: 
* doc/archive/inst_svn.texi: 
* doc/archive/inst_tar.texi: 
* doc/archive/lectures.txt: 
* doc/archive/rgui-doc.txt: 
* doc/archive/rmh-talk.tex: 
* doc/archive/rsn.txt: 
* doc/archive/slverb.sty: 
* doc/dir.txt: 
* doc/name-completion.txt: 
* etc/R-ESS-bugs.R: 
* etc/R-ESS-bugs.el: 
* etc/R-error-patterns.R: 
* etc/completion_ideas.R: 
* etc/gpl-check: 
* etc/other/config.guess: 
* etc/other/pkg1/DESCRIPTION: 
* etc/other/pkg1/NAMESPACE: 
* etc/other/pkg1/R/D1tr.R: 
* etc/other/pkg1/man/D1tr.Rd: 
* etc/other/sje-ess-notes.txt: 
* etc/pkg-Maintainers: Remove
```

**Comment by vspinu** [comment]
Well, I am unsure as well. Waiting for others to veto some of those files. IMO those are noise interfering with the development.

**Comment by jabranham** [comment]
Assuming no objections, I'll merge this by the end of the week @mmaechler @lionel-

**Comment by mmaechler** [comment]
I don't understand why these should be removed... why should they "interfere with development"?
We all know they are not part of the "source code" or "docs" properly.
I'd prefer  to keep important and historical info in there, rather than totally relying on info that is not part (of "our files"), such as github issues.   Notably I've been updating and adding to `etc/ESS-R-Bugs.R`  because I understand R code  (but don't understand how to read even less *write* regression test.

Why eradicate all roots of ESS who has been the longest existing Free Software in statistics? 
I don't want to be grouchy, but changes just to have everything historical gone are not according to my taste.

**Comment by jabranham** [comment]
> I don't understand why these should be removed... why should they "interfere with development"?
> We all know they are not part of the "source code" or "docs" properly.

We do, but people new to ESS don't. As a newcomer, if I see a file labelled `install-sh` at the top-level, I tend to assume it's a useful way to install the program. In our case, it's not.

> I'd prefer to keep important and historical info in there, rather than totally relying on info that is not part (of "our files"), such as github issues.

github issues are pretty integral to ESS development, most commit messages reference an issue or PR. Github provides a way to export these, so they aren't locked in or anything. It would be nice if git included the issues somehow, perhaps in the future a VCS will (I think [fossil](https://fossil-scm.org/index.html/doc/trunk/www/index.wiki) might)

> Notably I've been updating and adding to `etc/ESS-R-Bugs.R` because I understand R code (but don't understand how to read even less _write_ regression test.

But it's not clear whether that file contains solved bugs, current bugs, or whatever. It's also *much* better to write regression tests that run on travis so that we can catch them automatically. I'm happy to write regression tests for you if you say what the test should be. They're usually pretty simple to write.

> Why eradicate all roots of ESS

It's not eradicated; it's in the git history. It's always accessible for developers. And, even better, we're not putting files on users computers that don't actually get used (or, worse, contain incorrect documentation or code since we no longer keep them up-to-date).

**Comment by lionel-** [comment]
Alex is right that the roots of ESS will never be eradicated. Github even gives you an easy way to consult the past. You can browse all the recorded point in times (git tags) at https://github.com/emacs-ess/ESS/releases. For instance, here is the repository for the 12.03 release, the oldest tag in the repo: https://github.com/emacs-ess/ESS/tree/v12.03.

I don't think keeping adding files to the repo in an unorderly fashion is useful for the memory of the project. On the other hand, removing clutter makes the important stuff more easily findable. Instead of keeping old files around, I think it would be more useful for ESS archeology to push more tags corresponding to earlier releases. 2012 is way too short a memory for ESS :/

>  Notably I've been updating and adding to `etc/ESS-R-Bugs.R` because I understand R code (but don't understand how to read even less _write_ regression test.

We could have a `test/manual/` folder to put such files currently in use?

**Comment by mmaechler** [comment]
You have good points.   Maybe  move the ESS-R-Bugs.R   to a new location and only remove the rest?

NB: I'll be mostly offline (definitely off work) for a week of vacations now.

**Comment by mmaechler** [comment]
You have good points.   Maybe  move the ESS-R-Bugs.R   to a new location and only remove the rest?

NB: I'll be mostly offline (definitely off work) for a week of vacations now.

**Comment by jabranham** [comment]
OK, I've moved R-ESS-bugs.R under test/manual. Will merge later this week unless I hear otherwise.

**Pull request merged**
