### PR TITLE
Make `Makeconf` portable.

### PR DESCRIPTION
**Pull request by lq**
`which` does not have `-s` option on Linux.

### CODE REVIEW

**Comment by vspinu** [comment]
But `command` is not available either.  Or it's some GNU Make thingy? 

@rsparapa you added that line recently. Could you please have a look? I think we can safely remove `-s` option.

**Comment by rsparapa** [comment]
Yeah, I don't know what command is either.  Here's what I have now tested on Linux and macOS which should do it.  DOWNLOAD=$(shell which wget > /dev/null && echo 'wget -O -' || which curl)
However, the purpose of DOWNLOAD is to get julia-mode.el.  But this target is only grabbed once; after that you have it and it doesn't get it again.  So, I think the julia-mode.el target of lisp/Makefile should be performed every time not just once.

**Comment by lq** [comment]
That must be a bug of `make` on your system. `command` is a POSIX standard utility (http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html):

> The command -v and -V options were added to satisfy requirements from users that are currently accomplished by three different historical utilities: type in the System V shell, whence in the KornShell, and which in the C shell. Since there is no historical agreement on how and what to accomplish here, the POSIX command utility was enhanced and the historical utilities were left unmodified. The C shell which merely conducts a path search. The KornShell whence is more elaborate-in addition to the categories required by POSIX, it also reports on tracked aliases, exported aliases, and undefined functions.

**Comment by lq** [comment]
On my Debian box `command` is not found too. It is implemented as a shell built-in function there, but `make` failed to handle it. However, `DOWNLOAD != command -v wget && echo ' -O -' || command -v curl` is OK. Conversely, on my mac, `$(shell ...)` works but `!=` does not. For now, it may be better just dropping the `-s` option.

**Comment by lq** [comment]
@mmaechler That's irrelevant. Now it is downloaded only once. Better make julia-emacs a submodule?

**Comment by vspinu** [comment]
That was the original idea, but it's hard (impossible?) given that julia-mode.el is part of the huge julia repo and we don't want to pull in the whole repo.

**Comment by rsparapa** [comment]
Martin: Just droping the invalid '-s' as was proposed as well, seems feasible.
Rodney: No, just dropping -s is not correct.  You need do the following:
DOWNLOAD=$(shell which wget > /dev/null && echo 'wget -O -' || which curl)

**Comment by lq** [comment]
@vspinu `julia-mode.el` resides in https://github.com/JuliaEditorSupport/julia-emacs/, which essentially only contain the lisp file.

**Comment by vspinu** [comment]
This wasn't the case before. It should be submodule then, of course.

**Comment by rsparapa** [comment]
Change made.
DOWNLOAD=$(shell which wget > /dev/null && echo 'wget -O -' || which curl)

**Pull request closed without merging**
