### PR TITLE
Filling call arguments

### PR DESCRIPTION
**Pull request by lionel-**
The first commit fixes some bugs where refilling would overlap over the code following a roxygen block.

The second implements a new setting `ess-fill-calls` to allow refilling of call arguments. When it is non-nil, calling `(fill-paragraph)` when point is inside a call will indent and format all arguments according to `fill-column`. When called with a prefix, it formats them according to one argument per line.

### CODE REVIEW

**Comment by vspinu** [comment]
Is this related and fixes this issue https://stat.ethz.ch/pipermail/ess-help/2015-August/010641.html ?

I couldn't reproduce it.

**Comment by lionel-** [comment]
Hmm it looks related but I can't reproduce it either, with master or this branch. Though this branch does fix an infinite loop occurring when I `(fill-paragraph)` the generated roxy block.

I didn't know ESS could generate roxygen blocks btw, that's nice!

I found a but with call filling, I'll upload a fix.

**Comment by lionel-** [comment]
> I found a but with call filling, I'll upload a fix.

Fixed.

**Comment by lionel-** [comment]
When I have time I may do the same for continuations. So that long lines like this can be refilled easily:

```
fit_outreach <- lm(registered ~ outreach_action + log_income + urban + retired_pc + single_pc + region, data_eu)
```

And as for calls, without prefix it would arrange the continuations according to `fill-column`, while with prefix it would arrange them as one expression per line.

**Comment by vspinu** [comment]
> When I have time I may do the same for continuations

That would be great. Filling of code is a big weakness with ESS.

**Comment by vspinu** [comment]
This change is awesome. Thanks.

**Pull request merged**
