### PR TITLE
Archive historical versions of ESS in the repository

### PR DESCRIPTION
**Pull request by lionel-**
I would like to record the historical versions of ESS into the repository, for archiving purposes. The earliest revision of ESS is April 4th 1997, so we're missing at least 5 years of development. This PR creates a parallel git history for versions that were not revisioned. It includes the very first two versions of S-mode which are still available in the statlib archive at http://ftp.uni-bayreuth.de/math/statlib/S/. 

The first commit includes S-mode 2.1 by Doug Bates, Ed Kademan, and Frank Ritter. The second updates to 3.4 by David Smith. The commits were manufactured to reflect the original authors and release dates.

We're still missing 3.5, 4.0, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, and 4.8.MM6.XE3. The version after that is 5.0 which can be found at https://github.com/emacs-ess/ESS/commit/8918012bc. We can add these versions on top of the parallel history if we ever come across them. @mmaechler perhaps you still have some old tarballs somewhere?

When merged, this will be saved in the `archive` branch. We should then push release tags to record them properly, and the branch can be deleted.

### CODE REVIEW

**Comment by jabranham** [comment]
Thanks for looking into this! Out of curiosity, what prompted it? 

> When merged, this will be saved in the archive branch. We should then push release tags to record them properly, and the branch can be deleted.

So these commits will just not ever exist on the `master` branch?

**Comment by lionel-** [comment]
> Thanks for looking into this! Out of curiosity, what prompted it?

I had the idea when we discussed about removing unused historical files: https://github.com/emacs-ess/ESS/pull/821#issuecomment-462021451

I've already collected commit hashes for all ESS releases. The next step is to push the missing tags on the repo. I think annotated tags are best, with the NEWS of the release documented in the tag. These annotated tags have an author and an authordate, which should be set to the person who did the release and the date they did it. They probably don't need to be signed.

> So these commits will just not ever exist on the master branch?

That's right. Unfortunately it's not possible to include them in the master history without rehashing the whole thing.

**Comment by jabranham** [comment]
> I've already collected commit hashes for all ESS releases. The next step is to push the missing tags on the repo. I think annotated tags are best, with the NEWS of the release documented in the tag. These annotated tags have an author and an authordate, which should be set to the person who did the release and the date they did it. They probably don't need to be signed.

Sounds good to me. I wonder if we should start including the release news in our more contemporary tags...

> Unfortunately it's not possible to include them in the master history without rehashing the whole thing.

That's what I figured. Still will be nice, I suppose. Thanks for looking into this!

**Comment by mmaechler** [comment]
Thank you @lionel- for doing this. I've now searched a bit, and did not find earlier ESS versions than 5.1, so you got even further back than I could have ...

**Comment by vspinu** [comment]
How will this work for the future releases? You want to include the code, right? Does this mean swashing the whole release into the archive?

**Comment by lionel-** [comment]
This history will be completely independent from new releases. It's only for releases up to 5.0.

**Comment by lionel-** [comment]
These releases can now be visited at:

https://github.com/emacs-ess/ESS/tree/v2.1
https://github.com/emacs-ess/ESS/tree/v3.4

I have also added them to the release page for discoverability. They can be found in the very last page: https://github.com/emacs-ess/ESS/releases?after=v12.09-2

**Comment by jabranham** [comment]
Thanks! Can we delete the `archive` branch?

**Comment by lionel-** [comment]
We could, the tags themselves prevent garbage collection.

**Comment by jabranham** [comment]
Sorry, I guess what I should've asked is if you're OK removing it. Is there any reason to keep it around (if, e.g. you were planning on adding more versions later on)?

**Comment by lionel-** [comment]
no worries I just deleted it, I guess we can easily add it back if needed to add new versions.

**Pull request merged**
