### PR TITLE
Rewrite ess-rutils

### PR DESCRIPTION
**Pull request by jabranham**
This is a complete re-write of the functionality in ess-rutils so that we can keep this file when we contribute ESS to GNU Emacs.

The commit messages should be clear, let me know if there's something I missed.

### CODE REVIEW

**Comment by vspinu** [comment]
How much of these could be used on a routine basis by a generic user? Would it make sense to move those (all?) into the core?

**Comment by jabranham** [comment]
> How much of these could be used on a routine basis by a generic user? 

Most/all could be

> Would it make sense to move those (all?) into the core?

Yes, I was going to propose this later, but I can move it all into `ess-r-mode.el` if everyone's fine with that. Assuming we want to do that, should we remove `ess-rutils.el` or keep it as an empty file (in `lisp/obsolete`?) in case people `(require 'ess-rutils)` in their config?

**Comment by vspinu** [comment]
> or keep it as an empty file (in lisp/obsolete?) in

Yes. In the lisp for now as MELPA still doesn't fetch obsolete dir. Will try to PR a fix to them this week.

**Comment by jabranham** [comment]
OK, I've done that. Will merge soonish.

**Pull request merged**
