### PR TITLE
Don't link function arguments in help buffers

### LINKED ISSUE #855: Don't link arguments from functions in help buffers
e.g. `?lm` shouldn't link `data` since it is probably referring to the argument, not the data function.

See #848

### PR DESCRIPTION
**Pull request by jabranham**
Closes #855

### CODE REVIEW

**Comment by jabranham** [comment]
Travis doesn't like this for whatever reason, but works fine locally for me, both in batch and interactively. I'll take a look later I guess.

**Comment by vspinu** [comment]
`Process R<1> is not running, but others are. Switch? (y or n)` probably means that process exited earlier than expected and there are other processes. Looks like we are leaking processes in our tests somehow.

**Comment by jabranham** [comment]
Indeed. But since I can't reproduce it locally it's hard to track down.

Also, not sure if it's related but `ess-r-package-auto-no-activation-in-shell-test` fails locally for me, but only in batch, not interactively.

**Comment by jabranham** [comment]
"Fixed" the tests by marking that one to run only if interactive. Merged to master.

**Pull request merged**
