### PR TITLE
Small stylistic simplifications to the process-restore logic

### PR DESCRIPTION
**Pull request by vspinu**
@lionel-  I am trying to catch-up. Before we move further on this I would like to propose a few stylistic simplifications.

I think restoring in ordinary filter is the right aproach, but it is still not quite working and it's unclear why.

### CODE REVIEW

**Comment by lionel-** [comment]
> @lionel- I am trying to catch-up. Before we move further on this I would like to propose a few stylistic simplifications.

Thank you. Unfortunately I've already moved further in https://github.com/lionel-/ESS/commit/3cabdc51 :) Would you mind waiting for this work to be merged?

A few comments already:

- I think it makes sense to keep a `cmd-` prefix for everything related to `ess-command`. I've added more of these cmd prefixed properties in the linked commit.
- I like plist for user-facing data structures, but for the backend alist are more robust to programming errors. It's harder to inverse keys and values for instance.

**Comment by vspinu** [comment]
> I think it makes sense to keep a cmd- prefix for everything related to ess-command

The process-restore property might be used in the future from other places as well. I don't see it as `ess-command` specific. It's more like `oridinary-filter` specific.

> t's harder to inverse keys and values for instance.

 For complex nested data structures, yes of course, but here not relevant for 3 element plist. The benefit of plist+keywords in this concrete example is that it's much nice for the code. 

> Unfortunately I've already moved further in lionel-@3cabdc5 :) Would you mind waiting for this work to be merged?

Sure go head, but I wanted to discuss that exact piece of code first. My hunch is that we can do without that search, but it's just a hunch. The start string also is problematic when command output is displayed to the user. (e.g. C-c C-e C-e).

Maybe it would be a bit easier to rebase for you, as I have more small changes here. Not a big deal either way.

**Comment by lionel-** [comment]
> The process-restore property might be used in the future from other places as well. I don't see it as ess-command specific. It's more like oridinary-filter specific.

Good point but I think it's unclear that this data structure will be generic for other cases. How about we store a closure to be called once the proc is available again?

> For complex nested data structures, yes of course, but here not relevant for 3 element plist. The benefit of plist+keywords in this concrete example is that it's much nice for the code.

ok let's switch to plists.

**Comment by vspinu** [comment]
> How about we store a closure to be called once the proc is available again?

Not bad, cleaner and more generic. Basically moving `ess--command-proc-restore` into a lambda locally. No plists/alists required. I like it.

**Pull request closed without merging**
