### PR TITLE
Improve flymake docs

### PR DESCRIPTION
**Pull request by jabranham**
- Add flymake node to texi file
- Add flymake announcement to doc/newfeat.texi
- Address M-x checkdoc complaints in ess-r-flymake.el

### CODE REVIEW

**Comment by vspinu** [comment]
Perfect. Thanks!

**Comment by vspinu** [comment]
BTW, I think .rlint config file is not picked up from the current dir or package root. Could you please check this up? 

I am not even sure what should be the right behavior here. Should .rlint overwrite ESS setup completely, or only those values which are explicitly listed in .rlint?

**Comment by jabranham** [comment]
This is probably due to https://github.com/jimhester/lintr/issues/65

Maybe setting the 'default-directory' of the flymake buffer to the 'default-directory' of the source buffer would fix it?

**Comment by jabranham** [comment]
Hrm... maybe not, since that buffer already shares 'default-directory' with the source buffer. I'll look into it (and open a separate issue).

**Pull request merged**
